AllowReconnect: true

CombatTagging: true

PlayerEliminationDelay: 180

# This requires the team manager to be enabled
ExtendedSpawnLocations: true

# Set to true for legacy version where you can destroy blocks before the game starts
DisableEarlyBlockBreakCheck: false

# Set to true to not use the default game lobby
DontUseGameLobby: false

# Set to true to not play the wither death sound on end
DisableDefaultEndSound: false


DisableBuiltInCountdownSound: false
DisableActionBar: false
DisableChatCountdown: true
DisableTitleCountdown: false

ShuffleSpawnLocations: false