allow_reconnect: true

combat_tagging: true

player_elimination_delay: 180

# This requires the team manager to be enabled
extended_spawn_location: true

auto_start_countdown: true

# Set to true for legacy version where you can destroy blocks before the game starts
disable_early_block_break_check: false

# Set to true to not use the default game lobby
disable_novacore_gamelobby: false