name: NovaSurvivalGames
main: net.novauniverse.games.survivalgames.SurvivalGamesPlugin
description: Novauniverse SurvivalGames
version: 2.0.0
api-version: 1.13
depend: [NovaCore, NovaCoreGameEngine]
softdepend: [NovaGamesTarget, NovaCoreGameEnginePlus]

authors: [Zeeraa, NovaUniverse]

permissions:
  survivalgames.modifier.select:
    description: Allow user to select modifier
    default: op