name: NovaSurvivalGames
main: net.novauniverse.games.survivalgames.NovaSurvivalGames
description: Novauniverse SurvivalGames
version: 1.0
api-version: 1.13
depend: [NovaCore, NovaCoreGameEngine]
softdepend: [NovaGamesTarget]